### ISSUE TITLE
Unable to connect using Wallet connect.

### ISSUE THREAD

**Issue by Devender1703** [citydaoproject/parcel-0-claim-portal#5]
Steps to reproduce. 
1. Connect -> Wallet Connect. 

It throws following error 

`Unhandled Runtime Error
Error: Missing one of the required parameters: rpc or infuraId`

**Comment by trkaplan** [comment]
Hi @Devender2608 thanks for sharing.
Did you include an .env file in your local folder? This may caused that error. I can't reproduce this.
