### ISSUE TITLE
The frontend throws error when we do 'Claim Plots' 

### ISSUE THREAD

**Issue by Devender1703** [citydaoproject/parcel-0-claim-portal#6]
steps to reproduce. 

1. Connect metamask 
2. Claim Plots. 

`Unhandled Runtime Error
Error: invalid BigNumber string (argument="value", value="NaN", code=INVALID_ARGUMENT, version=bignumber/5.6.0)`

**Comment by trkaplan** [comment]
This is resolved. Thanks for reporting.
